### ISSUE TITLE
Players Can't Use Faction Pets To Attack Neutral Targets

### ISSUE THREAD

**Issue by ziimxe** [Thrax989/Project-Phoenix#112]
The ability to use faction pets to attack neutral targets was on before the update. It is also listed as a feature on SWGemu's server listing for Project Phoenix.

**Comment by Thrax989** [comment]
I'll up date the server listing with the updates soon with what was added / changed faction pets wont attack neutrals again . If you want to use attacks on Neutrals use regular pets. will beef up be and ch little bit more soon to make pets more viable for everyone instead of making the faction pets the go to for everything .
